apiVersion: oci.oracle.com/v1beta1
kind: AutonomousDatabases
metadata:
  name: oracledb
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaabwqnkg5r4sgb72edair3gaxqckws6p2qgxlyq67mnnqxvntwm4vq
  displayName: oracledb-version
  dbName: oracledb-version
  dbWorkload: OLTP
  isDedicated: false
  dbVersion: 19c
  dataStorageSizeInTBs: 1
  cpuCoreCount: 1
  adminPassword:
    secret:
      secretName: admin-secret
  isAutoScalingEnabled: false
  isFreeTier: false
  licenseModel: BRING_YOUR_OWN_LICENSE
  wallet:
    walletName: wallet
    walletPassword:
      secret:
        secretName: wallet-secret
  freeformTags:
  definedTags: 
